# Generated by Django 4.2.7 on 2025-08-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='true_false_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
