# Generated by Django 4.2.7 on 2025-08-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_answer_true_false_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'QCM'), ('open', 'Question ouverte')], default='mcq', max_length=20),
        ),
    ]
