# Generated by Django 4.2.7 on 2025-08-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='true_false_answer',
        ),
    ]
