# Generated by Django 4.2.7 on 2025-08-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_name',
            field=models.CharField(blank=True, choices=[('6eme', '6ème'), ('5eme', '5ème'), ('4eme', '4ème'), ('3eme', '3ème'), ('2nde', '2nde'), ('1ere', '1ère'), ('terminale', 'Terminale')], help_text="Classe de l'élève", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='class_name',
            field=models.CharField(blank=True, choices=[('6eme', '6ème'), ('5eme', '5ème'), ('4eme', '4ème'), ('3eme', '3ème'), ('2nde', '2nde'), ('1ere', '1ère'), ('terminale', 'Terminale')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
