# Generated by Django 4.2.7 on 2025-10-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_class_name_alter_studentprofile_class_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='class_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Élève'), ('teacher', 'Enseignant'), ('admin', 'Administrateur')], max_length=10),
        ),
    ]
